# Generated by Django 5.2.15 on 2026-06-08 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_update_tombo_3_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('deadline', models.DateField(verbose_name='prazo')),
                ('status', models.CharField(choices=[('OPEN', 'Aberta'), ('CLOSED', 'Encerrada')], default='OPEN', max_length=10, verbose_name='status')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='aberta em')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='encerrada em')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_inventory_audits', to=settings.AUTH_USER_MODEL, verbose_name='encerrada por')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_inventory_audits', to=settings.AUTH_USER_MODEL, verbose_name='aberta por')),
            ],
            options={
                'verbose_name': 'auditoria de inventario',
                'verbose_name_plural': 'auditorias de inventario',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItemMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200, verbose_name='motivo')),
                ('previous_department', models.CharField(blank=True, max_length=180, verbose_name='departamento anterior')),
                ('new_department', models.CharField(blank=True, max_length=180, verbose_name='novo departamento')),
                ('previous_responsible_person', models.CharField(blank=True, max_length=150, verbose_name='responsavel anterior')),
                ('new_responsible_person', models.CharField(blank=True, max_length=150, verbose_name='novo responsavel')),
                ('previous_status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('MAINTENANCE', 'Manutencao'), ('STORED', 'Em estoque'), ('RETIRED', 'Baixado')], max_length=20, verbose_name='status anterior')),
                ('new_status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('MAINTENANCE', 'Manutencao'), ('STORED', 'Em estoque'), ('RETIRED', 'Baixado')], max_length=20, verbose_name='novo status')),
                ('observation', models.TextField(blank=True, verbose_name='observacao')),
                ('photo', models.ImageField(upload_to='inventory/movements/photos/%Y/%m/', verbose_name='foto da movimentacao')),
                ('caution_document', models.FileField(upload_to='inventory/movements/cautions/%Y/%m/', verbose_name='cautela')),
                ('moved_at', models.DateTimeField(auto_now_add=True, verbose_name='movimentado em')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.inventoryitem', verbose_name='item')),
                ('moved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to=settings.AUTH_USER_MODEL, verbose_name='movimentado por')),
            ],
            options={
                'verbose_name': 'movimentacao de item',
                'verbose_name_plural': 'movimentacoes de itens',
                'ordering': ['-moved_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAuditItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_name', models.CharField(max_length=150, verbose_name='nome registrado')),
                ('snapshot_department', models.CharField(blank=True, max_length=180, verbose_name='departamento registrado')),
                ('snapshot_responsible_person', models.CharField(blank=True, max_length=150, verbose_name='responsavel registrado')),
                ('snapshot_status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('MAINTENANCE', 'Manutencao'), ('STORED', 'Em estoque'), ('RETIRED', 'Baixado')], max_length=20, verbose_name='status registrado')),
                ('snapshot_tombo_1', models.CharField(blank=True, max_length=80, verbose_name='tombo 1 registrado')),
                ('snapshot_tombo_2', models.CharField(blank=True, max_length=80, verbose_name='tombo 2 registrado')),
                ('snapshot_tombo_3', models.CharField(blank=True, max_length=80, verbose_name='tombo 3 registrado')),
                ('located', models.BooleanField(blank=True, null=True, verbose_name='equipamento localizado')),
                ('condition', models.CharField(blank=True, choices=[('GOOD', 'Boa'), ('FAIR', 'Regular'), ('POOR', 'Ruim'), ('INOPERATIVE', 'Inoperante')], max_length=20, verbose_name='condicao')),
                ('found_responsible_person', models.CharField(blank=True, max_length=150, verbose_name='responsavel encontrado')),
                ('observation', models.TextField(blank=True, verbose_name='observacao')),
                ('evidence_image', models.ImageField(blank=True, upload_to='inventory/audits/%Y/%m/', verbose_name='foto da conferencia')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='conferido em')),
                ('reviewed', models.BooleanField(default=False, verbose_name='revisado')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='revisado em')),
                ('applied_department', models.BooleanField(default=False, verbose_name='departamento aplicado')),
                ('applied_responsible_person', models.BooleanField(default=False, verbose_name='responsavel aplicado')),
                ('applied_status', models.CharField(blank=True, choices=[('ACTIVE', 'Ativo'), ('MAINTENANCE', 'Manutencao'), ('STORED', 'Em estoque'), ('RETIRED', 'Baixado')], max_length=20, verbose_name='status aplicado')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_items', to='inventory.inventoryaudit', verbose_name='auditoria')),
                ('found_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_findings', to='inventory.department', verbose_name='departamento encontrado')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_records', to='inventory.inventoryitem', verbose_name='item')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_inventory_items', to=settings.AUTH_USER_MODEL, verbose_name='revisado por')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_inventory_items', to=settings.AUTH_USER_MODEL, verbose_name='conferido por')),
                ('movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_record', to='inventory.inventoryitemmovement', verbose_name='movimentacao gerada')),
            ],
            options={
                'verbose_name': 'item de auditoria',
                'verbose_name_plural': 'itens de auditoria',
                'ordering': ['snapshot_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='inventoryaudit',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('status',), name='single_open_inventory_audit'),
        ),
        migrations.AddConstraint(
            model_name='inventoryaudititem',
            constraint=models.UniqueConstraint(fields=('audit', 'item'), name='unique_item_per_audit'),
        ),
    ]
