# Generated by Django 5.2.15 on 2026-06-08 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_movement_return_and_delivery_cautions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryaudititem',
            name='applied_status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Ativo'), ('MAINTENANCE', 'Manutencao'), ('STORED', 'Em estoque'), ('RETIRED', 'Baixado'), ('NOT_FOUND', 'Nao localizado')], max_length=20, verbose_name='status aplicado'),
        ),
        migrations.AlterField(
            model_name='inventoryaudititem',
            name='snapshot_status',
            field=models.CharField(choices=[('ACTIVE', 'Ativo'), ('MAINTENANCE', 'Manutencao'), ('STORED', 'Em estoque'), ('RETIRED', 'Baixado'), ('NOT_FOUND', 'Nao localizado')], max_length=20, verbose_name='status registrado'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Ativo'), ('MAINTENANCE', 'Manutencao'), ('STORED', 'Em estoque'), ('RETIRED', 'Baixado'), ('NOT_FOUND', 'Nao localizado')], default='ACTIVE', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='inventoryitemmovement',
            name='new_status',
            field=models.CharField(choices=[('ACTIVE', 'Ativo'), ('MAINTENANCE', 'Manutencao'), ('STORED', 'Em estoque'), ('RETIRED', 'Baixado'), ('NOT_FOUND', 'Nao localizado')], max_length=20, verbose_name='novo status'),
        ),
        migrations.AlterField(
            model_name='inventoryitemmovement',
            name='previous_status',
            field=models.CharField(choices=[('ACTIVE', 'Ativo'), ('MAINTENANCE', 'Manutencao'), ('STORED', 'Em estoque'), ('RETIRED', 'Baixado'), ('NOT_FOUND', 'Nao localizado')], max_length=20, verbose_name='status anterior'),
        ),
    ]
